# Generated by Django 3.2.16 on 2022-12-31 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='rollno',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
